apiVersion: v1
kind: Secret
metadata:
  name: event-secrets
  namespace: event-management
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-icy-base-an85ai5d-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  SPRING_DATASOURCE_USERNAME: "neondb_owner"
  SPRING_DATASOURCE_PASSWORD: "npg_mVB0OXb7Dtwx"
  JWT_SECRET: "EventManagementSystem2026NeonDBSecretKeyForJWTTokenHS512Algorithm12345678"
  JWT_EXPIRATION: "86400000"
